sudo: required
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -U pip setuptools"
  - "pip install -U Cython"
  - "pip install -r requirements.txt"
  - "pip install codecov pytest-cov"
  - python setup.py build_ext --inplace
script:
  - make lint
  - make dory-test
  - py.test spacegraphcats search --cov=.

after_success:
  - codecov
