sudo: required
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -U pip setuptools"
  - "pip install -U Cython"
  - "pip install -r requirements.txt"
  - "pip install https://github.com/dib-lab/khmer/archive/master.zip"
  - "pip install codecov pytest-cov"
  - python setup.py build_ext --inplace
script:
  - make lint
  - make test
  - make twofoo-test
  - py.test spacegraphcats --cov=.

after_success:
  - codecov
