name: spacegraphcats
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - bcalm=2.2.3
    - snakemake-minimal=5.20.1
    - cython
    - screed=1.0.1
    - sourmash<4
    - khmer=3.0.0a3
    - pandas=0.25.3
    - numpy
    - pytest=5.3.2
    - sortedcontainers=2.1.0
    - mypy=0.750
    - click=7.1.1
    - pyflakes
    - pip
    - pip:
      - https://github.com/dib-lab/pybbhash/archive/spacegraphcats.zip
